name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    strategy:
      matrix:
        version: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, gha-runner-x64, gha-runner-arm64, macos-latest]
    runs-on: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --lib
